Authentication and Authorization
center-for-threat-informed-defense/attack-workbench-frontend pull request #276
Opened 2022-01-20 17:51 UTC by clemiller

Authentication and authorization for users of the Workbench.

Summary of changes:
- Implements authentication and authorization with Anonymous and OpenID Connect (OIDC) authentication mechanisms. Users must be logged in to access the Workbench data. Resolves #192.
    - Adds `visitor`, `editor`, and `admin` permissions.
    - Adds route guarding to prevent users from accessing protected pages by directly manipulating the URL.
- Adds login and logout functionality. Users may access documentation pages without logging in. Resolves #266.
    - Adds a warning message that is displayed on login attempts made by users with a `pending` or `inactive` account status. These users are unable to login until the administrator either approves their access or marks them as active users.
    - Adds the user identity icon to the header which is displayed when a user is logged in. The logout option is present in the account options dropdown menu.
- Adds individual attribution, allowing logged in users to view who edited a given object. Individual attribution is not supported when the Workbench is configured to use anonymous authentication. Resolved in #191.
- Fixes an issue with creating new collections.

2022-02-21 13:21 UTC, IanDavila requested changes
This was an amazing addition to the codebase, thank you! Just made a small suggestion to see if that will remove the duplication that SonarCloud was alerting on.

2022-02-21 13:21 UTC, IanDavila commented on docs/changelog.md
> +## 16 February 2022
We'll need to update this date again and think if we want to release the marking definitions milestone as part of v1.2

2022-02-21 14:51 UTC, clemiller commented on app/src/app/app-routing-stix.module.ts
This is a really great idea, especially from a maintainability standpoint and it also helped with the duplication issues! Thanks for this suggestion!!

2022-02-21 14:55 UTC, IanDavila approved these changes
Looks great, thank you!

2022-02-28 16:33 UTC, jondricek commented on app/src/app/services/connectors/authentication/authentication.service.ts
> +     * Note: this does not log the user out of the OIDC Identity Provider
Can you edit this note to briefly identify what _does_ happen instead of what _doesn't_ happen?

2022-02-28 16:56 UTC, merged