Feature/teams pages
center-for-threat-informed-defense/attack-workbench-frontend pull request #462
Opened 2023-04-10 11:50 UTC by vince-a-m

- Added UserList component for displaying users
- Added AddUserDialog for user selection
- Added TeamsList and TeamsView components for displaying all teams and an individual team
- Added a CreateDialog component for getting inputs for a new object from the user.
- Added placehold REST API routes for CRUD operations on teams

2023-04-18 20:46 UTC, clemiller requested changes
This is a great start to the Teams interface! The overall workflow of creating/editing teams and updating the user lists looks good. I've made a few comments below on some suggested improvements. A couple of other thoughts:

- [ ] I haven't looked through the code smells reported by sonarcloud, so if you haven't already, it may be worth looking into to see if some of those could be resolved.
- [ ] Function docs - would you mind adding these to explain what each function does? It'll make it easier for others to understand each function's purpose and how they're used
- [ ] The spacing around the teams header and the "create a new team" button is a little tight in comparison to the other Workbench pages. Similar spacing issues with the list of users on the team view page:
![image](https://user-images.githubusercontent.com/48832936/232863878-ed9c8763-959e-4d25-b0b1-3c55eb99c7af.png)
![image](https://user-images.githubusercontent.com/48832936/232863944-0671fce4-73d8-4509-914e-a926f128209a.png)

2023-04-19 12:55 UTC, vince-a-m commented on app/src/app/classes/authn/team.ts
> +import { UserAccount } from './user-account';
They are going to be needed once the teams actually exist, if they aren't used after that I'll remove them.

2023-04-19 12:56 UTC, vince-a-m commented on app/src/app/classes/authn/team.ts
> +        } else { this.modified = new Date(); }*/
Yes

2023-04-19 12:58 UTC, vince-a-m commented on app/src/app/views/admin-page/admin-page.component.html
> +                      <mat-icon>groups</mat-icon>
:)

2023-04-19 13:07 UTC, vince-a-m commented on app/src/app/classes/authn/team.ts
> +    }
Will add once there API endpoints exist

2023-04-19 13:08 UTC, vince-a-m commented on app/src/app/classes/authn/team.ts
> +    }
Yeah, I'm just mocking the API for the time being so I did what I had to do to get it run.  Will change once the API exists

2023-04-19 13:28 UTC, vince-a-m commented on app/src/app/components/users-list/users-list.component.html
@clemiller Sorry, I don't know what this means.  Could you elaborate?

2023-04-19 13:56 UTC, vince-a-m commented
A lot of the code smells are due to weird hacky workarounds related to the API not actually existing yet.  

Can do with adding the comments to the functions 👍

2023-04-19 14:32 UTC, vince-a-m commented on app/src/app/views/admin-page/teams/teams-view-page/teams-view-page.component.html
> +        }"></app-descriptive-property>
Made a fix, might need some work

2023-05-11 18:12 UTC, clemiller requested changes
I ran into a couple of errors while I was testing out the teams interface:

- An error is thrown when a team is created without a description, as well as after clicking "edit" on a team without a description:

<img width="327" alt="image" src="https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/assets/48832936/3e4e5f12-0978-42f5-bd36-0eb049d3f3f1">

- Errors are thrown and the API crashes when an existing team is edited and given a non-unique name. The team name should be validated before sending the PUT request to the API and prevent the user from saving if it's not unique.

Also, if there are a lot of users in a Workbench instance, it might take a while to find all of the users to add to a team. Would it be possible to add searching for users in the add-dialog window?
<img width="747" alt="image" src="https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/assets/48832936/28715a80-b6e1-43f5-bc18-a6dab4d0649e">

2023-05-16 15:14 UTC, merged