Fix #517 Configurable Docker Compose exposed ports
center-for-threat-informed-defense/attack-workbench-frontend pull request #518
Opened 2023-11-14 09:42 UTC by MaurizioCasciano

This PR fixes #517 by allowing the use of environment variables in Docker Compose to configure the exposed ports.

2024-02-19 13:56 UTC, seansica requested changes
Please remove unnecessary environment variables from persisting in the container. The rest looks okay.

2024-02-19 13:56 UTC, seansica commented on docker-compose.yml
> +      BACKEND_PORT: "${BACKEND_PORT:-3000}"
Please remove this line.

2024-02-19 13:56 UTC, seansica commented on docker-compose.yml
> +      DATABASE_PORT: "${DATABASE_PORT:-27017}"
Please remove this line.

2024-07-15 09:53 UTC, Wheeler69 reviewed
nice

2024-07-22 16:43 UTC, seansica commented
This compose file has been superseded by the template available in the newer [Workbench Deployment](https://github.com/mitre-attack/attack-workbench-deployment) repo.

Thank you for your contribution.

2024-07-22 16:43 UTC, closed without merging